blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/jurialmunkey/skin.arctic.fuse/discussions/categories/feature-requests
    about: Feature requests should be made in the discussions section
